GET http://localhost:3000/items/ HTTP/1.1

####
GET http://localhost:3000/items/5f5eb07791713c507cb9146d HTTP/1.1

####

POST http://localhost:3000/items/ HTTP/1.1
content-type: application/json

{
    "name": "Item 1",
    "description": "This is Item 1",
    "quantity": 1
}
